# Python review

Short review about some core conepts in Python exemplified by objects in the Numpy library

Goals: 
- recap basic Python vocab
- practice markdown syntax

## Libraries and packages:

**library:** is a collection of code that we can use to perform specific tasks in our programs. It can be a single file or multiple files.

**NumPy:** 
- core library for numerical computing in Python
- many of the libraries use NumPy arrays as their building blocks
- computations on NumPy objects are optimized for speed and memory usage


Let's import NumPy with its **standard abbreviation** `np`:
import numpy as np

(esc + press M twice --> convert code cell to markdown)

## Variables 
** variable:** a name we 

In [1]:
import numpy as np

# Assign a small array to a variable 
a = np.array([ [1,1,2], [3,5,8] ])

To view a variables value from our Jupyter notebook:

In [2]:
# Run a cell with variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [3]:
# Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]
