# Python review

Short review about some core conepts in Python exemplified by objects in the Numpy library

Goals: 
- recap basic Python vocab
- practice markdown syntax

## Libraries and packages:

**library:** is a collection of code that we can use to perform specific tasks in our programs. It can be a single file or multiple files.

**NumPy:** 
- core library for numerical computing in Python
- many of the libraries use NumPy arrays as their building blocks
- computations on NumPy objects are optimized for speed and memory usage


Let's import NumPy with its **standard abbreviation** `np`:
import numpy as np

(esc + press M twice --> convert code cell to markdown)

## Variables 
** variable:** a name we 

In [1]:
import numpy as np

# Assign a small array to a variable 
a = np.array([ [1,1,2], [3,5,8] ])

To view a variables value from our Jupyter notebook:

In [2]:
# Run a cell with variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [3]:
# Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Naming convention: Use `snakecase` for naming variables

This is the convention that we will use in the course.

*Why?*  `my-variable` or `MyVariable` or `myVariable` are all valid ways to write variables however PEP 8 - Style Guide for Python code reccomends snake_case.

**Remember that variable names should be both description and concise!** 

## Objects

**object:** (informally) is a bundle of *properties* and *actions* about something specific.

*Ex. 
Object: data frame [is the **thing** that you are referencing] 
Properties: number of rows, names of columns, and date created
Actions: selecting a specific row or adding a new column*

A variable is the name we give a specific object and the same object can be referenced by different variables. 

In practice, we can often use the word variable and object interchangeably.

## Types

Every object in Python has a **type**, the type tells us what kind of objects we have.
We can also call the type of an object, the **class** of an object. So class and object both mean what kind of object we have.

In [4]:
# print the array that we formerly made
print(a)

[[1 1 2]
 [3 5 8]]


In [5]:
# See the type/calss of a variable/object by using the `type` function
# This is a common way to start troubleshooting - ie. use to make sure you know what type of data you are working with 
type(a)

numpy.ndarray

The numpy.ndarray is the core object/dat type of the NumPy package

In [6]:
print(a[0,0])
type(a[0,0])

1


numpy.int64

`numpy.int64` is not the standard Python integer tpe `int`.
`numpy.int64` is a special data type in Numpy telling us that 1 is an integer stored as a 64-bit number

Check-in: access the value 5 in array `a`

In [8]:
a[1,1]  # remember that index starts with 0 for python

5

## Functions

`print` was our first example of a Python **function**

Functions take in a set of **arguments**, separated by commas, and use those arguments to create an **output**.

In this course we'll be using argument and parameter interchangeably, but they do have slightly different meanings.

We can ask for info about what a function does by executing `?` followed by the function name: 

In [9]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


What we obtain is a **docstring** a special type of comment that is used to document how a function or a class or a module works
Made up of:
- name(all the parameters/aguments)
- short description of what it does
- list of parameters and what they do in the function

Notice that there are different types of arguments inside the functions parenthesis
Roughly speaking, a function has two types of arguments: 

- **non-operational arguments**: arguments *you* have to specifiy for the function to work
- **optional arguments**: arguments that are pre-filled with a fegault value by the function,  but you can override them. *Optional arguments appear inside the parenthesis () in the form `optional_argument = default`*

*Ex. 
`end` is a parameter in `print` with default value a new line
We can pass the value `:-)` to this parameter so that it finishes the line with `:-)` instead:

In [12]:
print('Change the end parameter to', end=' :-)')

Change the end parameter to :-)

## Attributes and methods

An object in Python has attributes and methods.

- **attribute**: a property of the object, some piece of information about it
- **method**: a procedure associated with an object, so it is an action/function where the main ingredient is the object itself.

## Check-in

Make a diagram/concept for a class `fish`:

Attributes:
- Species
- Color
- Length
- Weight

Methods:
- swim()
- eat()
- poop()
- spawn()

*Ex.

Numpy arrays have many methods and attributes.


In [13]:
# T is an example of an attribute, it returns the transpose of array
print(a.T)

[[1 3]
 [1 5]
 [2 8]]


In [14]:
type(a.T)

numpy.ndarray

In [17]:
# shape another attribute that tells ust he shape of the array
# (rows, columns) 
print(a.shape)

print(type(a.shape))

(2, 3)
<class 'tuple'>


In [21]:
# ndim is an attribute holding the number of array dimensions
print('dim:', a.ndim, '| type:', type(a.ndim))

dim: 2 | type: <class 'int'>


Attributes can have many different data types.

*Some examples of methods:*

In [22]:
# the min method returns the minimum value in the array along a specified axis 
print(a)
a.min(axis=0)

[[1 1 2]
 [3 5 8]]


array([1, 1, 2])

In [23]:
# Run min method with axis
a.min()

1

In [24]:
# method tolist() transforms array to a list
a.tolist()

[[1, 1, 2], [3, 5, 8]]

In [25]:
print(a)

[[1 1 2]
 [3 5 8]]


In [26]:
b = a.tolist()

In [27]:
print(b)

[[1, 1, 2], [3, 5, 8]]


# Exercise

1. Read the print function help. What is the type of argument sep ? is this a default or non-default argument? why?

*answer: sep is a parameter for the separator it is an optional parameter with space as default, change by setting sep = 'desired parameter'*


In [28]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


2. Create two new variables, one with the integer value 77 and another one with the string 99

3. Use your variables to print 77%99%77 by changing hte value of one of the default arguments in `print`

In [29]:
var77 = 77
var99 = '99'
print(var77, var99, sep = '%')


77%99
